### ISSUE TITLE
Cannot use Commander & Stencil in the same project

### ISSUE THREAD

**Issue by maxkramerbcgdv** [kylef/Commander#46] opened 2017-01-05 09:56 UTC
Hi Kyle,

Thanks for your contributions to OSS, Stencil is incredibly useful for something that I'm working on!

I'm attempting to use both Commander and Stencil in the same project, however when attempting to run `swift package fetch` it's returning an error, as both libraries require Spectre.

It appears to be an issue with Swift PM not resolving the dependency correctly. What do you think?

I've attached a small project to demonstrate.

```
error: rename error: Directory not empty (66): 
/Users/kramer_max/Desktop/CommanderStencil/Packages/Spectre.git ->    /Users/kramer_max/Desktop/CommanderStencil/Packages/Spectre-0.7.2
```

Package.swift:

```
let package = Package(
    name: "cerberus",
    dependencies: [
        .Package(url: "https://github.com/kylef/Stencil.git", majorVersion: 0, minor: 7),
        .Package(url: "https://github.com/kylef/Commander.git", majorVersion: 0)
    ]
)
```

Cheers,
Max.

[CommanderStencil.zip](https://github.com/kylef/Commander/files/686941/CommanderStencil.zip)

**Comment by sclukey** [comment] 2017-01-05 13:44
The problem is that Stencil depends on `.../kylef/Spectre` while Commander depends on `.../kylef/Spectre.git`. Unfortunately, for SwiftPM the `.git` seems to matter

**Comment by maxkramerbcgdv** [comment] 2017-01-05 14:17
@sclukey I thought the same and tried pointing the Package.swift in Stencil to a url with the .git in a fork, but it still had the same issue: https://github.com/maxkramerbcgdv/Stencil.

**Comment by sclukey** [comment] 2017-01-05 15:10
Adding that commit to your fork won't fix it in two ways:

1. SwiftPM uses the latest tagged version, so just adding a new commit doesn't change the code that SwiftPM actually uses. It will checkout version 0.7.2 which still says has no `.git`. 
2. Only changing the dependency in Stencil won't fix it because the newest tagged release of PathKit (0.7.1) also does not use a `.git` extension on the Spectre dependency.

It's a bit of a mess, but I'm certain the `.git` is your issue

**Comment by maxkramerbcgdv** [comment] 2017-01-05 15:13
@sclukey you're right - I'll look into it further later on. Thanks for the help!

**Comment by kylef** [comment] 2017-02-21 13:41
Using Stencil 0.8 this problem should be resolved.

**Closed by kylef** 2017-02-21 13:41 UTC

**Comment by che1404** [comment] 2017-10-20 05:05
Hi @kylef , 
I'm having the exact same issue now. 
My Pacakge.swift points to versions 0.8.0 of both Commander and Stencil and SPM is not able to resolve.
Depending on Commander version 0.6.0 as @sclukey suggested works as a workaround, but of course I'd like to always use the last stable versions.
Having a look at Commander and Stencil's dependency on Spectre, I can see that Commander depends on the version 0.8, and Stencil on 0.7. Could it be the source of the problem?
